/* @generated by flare — do not edit. checksum: ad3f62888b8d */
/* Auto-generated by flare — do not edit */
import type { RouteData, TreeNode } from "@lovrozagar/flare/codegen"
import type { handler as _FlareHandler } from "../server"

const E: Record<string, TreeNode> = Object.create(null)
function S(o: Record<string, TreeNode>): Record<string, TreeNode> { return Object.assign(Object.create(null), o) }

const O0 = { static: { mode: "isr" } } as const
const O1 = { client: { staleTime: 0, prefetch: false } } as const
const O2 = {} as const

const R0: RouteData = {
	e: "route",
	f: "src/routes/[locale]/_root_/locale-home.page.tsx",
	o: O0,
	p: () => import("../routes/[locale]/_root_/locale-home.page").then(m => ({ default: m.route })),
	t: "r",
	v: "/[locale]",
	x: "[locale]/_root_/",
}
const R1: RouteData = {
	e: "route",
	f: "src/routes/_admin_/dashboard/dash.page.tsx",
	o: O0,
	p: () => import("../routes/_admin_/dashboard/dash.page").then(m => ({ default: m.route })),
	t: "r",
	v: "/dashboard",
	x: "_admin_/dashboard",
}
const R2: RouteData = {
	e: "route",
	f: "src/routes/_root_/(auth)/login/login.page.tsx",
	o: O0,
	p: () => import("../routes/_root_/(auth)/login/login.page").then(m => ({ default: m.route })),
	t: "r",
	v: "/login",
	x: "_root_/(auth)/login",
}
const R3: RouteData = {
	e: "route",
	f: "src/routes/_root_/(blog)/blog/[slug]/post.page.tsx",
	o: O0,
	p: () => import("../routes/_root_/(blog)/blog/[slug]/post.page").then(m => ({ default: m.route })),
	t: "r",
	v: "/blog/[slug]",
	x: "_root_/(blog)/blog/[slug]",
}
const R4: RouteData = {
	e: "route",
	f: "src/routes/_root_/(blog)/blog/list.page.tsx",
	o: O0,
	p: () => import("../routes/_root_/(blog)/blog/list.page").then(m => ({ default: m.route })),
	t: "r",
	v: "/blog",
	x: "_root_/(blog)/blog",
}
const R5: RouteData = {
	e: "route",
	f: "src/routes/_root_/(dc)/(inner)/(leaf)/deep-cache/index.page.tsx",
	o: O0,
	p: () => import("../routes/_root_/(dc)/(inner)/(leaf)/deep-cache/index.page").then(m => ({ default: m.route })),
	t: "r",
	v: "/deep-cache",
	x: "_root_/(dc)/(inner)/(leaf)/deep-cache",
}
const R6: RouteData = {
	e: "route",
	f: "src/routes/_root_/(dc)/(inner)/(leaf)/deep-cache/uncached/uncached.page.tsx",
	o: O1,
	p: () => import("../routes/_root_/(dc)/(inner)/(leaf)/deep-cache/uncached/uncached.page").then(m => ({ default: m.route })),
	t: "r",
	v: "/deep-cache/uncached",
	x: "_root_/(dc)/(inner)/(leaf)/deep-cache/uncached",
}
const R7: RouteData = {
	e: "route",
	f: "src/routes/_root_/[_]internal/hidden.page.tsx",
	o: O0,
	p: () => import("../routes/_root_/[_]internal/hidden.page").then(m => ({ default: m.route })),
	t: "r",
	v: "/_internal",
	x: "_root_/_internal",
}
const R8: RouteData = {
	e: "route",
	f: "src/routes/_root_/about/about.page.tsx",
	o: O0,
	p: () => import("../routes/_root_/about/about.page").then(m => ({ default: m.route })),
	t: "r",
	v: "/about",
	x: "_root_/about",
}
const R9: RouteData = {
	e: "route",
	f: "src/routes/_root_/files/[...path]/files.page.tsx",
	o: O0,
	p: () => import("../routes/_root_/files/[...path]/files.page").then(m => ({ default: m.route })),
	t: "r",
	v: "/files/[...path]",
	x: "_root_/files/[...path]",
}
const R10: RouteData = {
	e: "route",
	f: "src/routes/_root_/home.page.tsx",
	o: O0,
	p: () => import("../routes/_root_/home.page").then(m => ({ default: m.route })),
	t: "r",
	v: "/",
	x: "_root_/",
}
const R11: RouteData = {
	e: "route",
	f: "src/routes/_root_/optional-locale/[[locale]]/opt.page.tsx",
	o: O0,
	p: () => import("../routes/_root_/optional-locale/[[locale]]/opt.page").then(m => ({ default: m.route })),
	t: "r",
	v: "/optional-locale/[[locale]]",
	x: "_root_/optional-locale/[[locale]]",
}
const R12: RouteData = {
	e: "route",
	f: "src/routes/_root_/sitemap.xml/sitemap.page.tsx",
	o: O2,
	p: () => import("../routes/_root_/sitemap.xml/sitemap.page").then(m => ({ default: m.route })),
	t: "x",
	v: "/sitemap.xml",
	x: "_root_/sitemap.xml",
}
const R13: RouteData = {
	e: "route",
	f: "src/routes/_root_/users/[id]/user.page.tsx",
	o: O0,
	p: () => import("../routes/_root_/users/[id]/user.page").then(m => ({ default: m.route })),
	t: "r",
	v: "/users/[id]",
	x: "_root_/users/[id]",
}

export const routeTree: TreeNode = { p: { n: "locale", r: R0, s: E }, r: R10, s: S({ dashboard: { r: R1, s: E }, login: { r: R2, s: E }, blog: { p: { n: "slug", r: R3, s: E }, r: R4, s: E }, "deep-cache": { r: R5, s: S({ uncached: { r: R6, s: E } }) }, _internal: { r: R7, s: E }, about: { r: R8, s: E }, files: { c: { n: "path", r: R9, s: E }, s: E }, "optional-locale": { q: { n: "locale", r: R11, s: E }, s: E }, "sitemap.xml": { r: R12, s: E }, users: { p: { n: "id", r: R13, s: E }, s: E } }) }

export const layouts: Record<string, () => Promise<{ default: unknown }>> = {
	"[locale]/_root_": () => import("../routes/[locale]/_root_/locale.root-layout").then(m => ({ default: m["route"] })),
	"_admin_": () => import("../routes/_admin_/admin.root-layout").then(m => ({ default: m["route"] })),
	"_root_/(auth)": () => import("../routes/_root_/(auth)/auth.layout").then(m => ({ default: m["route"] })),
	"_root_/(blog)": () => import("../routes/_root_/(blog)/blog.layout").then(m => ({ default: m["route"] })),
	"_root_/(dc)/(inner)/(leaf)": () => import("../routes/_root_/(dc)/(inner)/(leaf)/leaf.layout").then(m => ({ default: m["route"] })),
	"_root_/(dc)/(inner)": () => import("../routes/_root_/(dc)/(inner)/inner.layout").then(m => ({ default: m["route"] })),
	"_root_/(dc)": () => import("../routes/_root_/(dc)/dc.layout").then(m => ({ default: m["route"] })),
	"_root_": () => import("../routes/_root_/root.root-layout").then(m => ({ default: m["route"] })),
}

export const layoutModuleIds: Record<string, string> = {
	"[locale]/_root_": "src/routes/[locale]/_root_/locale.root-layout.tsx",
	"_admin_": "src/routes/_admin_/admin.root-layout.tsx",
	"_root_/(auth)": "src/routes/_root_/(auth)/auth.layout.tsx",
	"_root_/(blog)": "src/routes/_root_/(blog)/blog.layout.tsx",
	"_root_/(dc)/(inner)/(leaf)": "src/routes/_root_/(dc)/(inner)/(leaf)/leaf.layout.tsx",
	"_root_/(dc)/(inner)": "src/routes/_root_/(dc)/(inner)/inner.layout.tsx",
	"_root_/(dc)": "src/routes/_root_/(dc)/dc.layout.tsx",
	"_root_": "src/routes/_root_/root.root-layout.tsx",
}

/* Route type registry — auto-generated */
declare module "@lovrozagar/flare/codegen" {
	interface FlareRegister {
		routes: {
			"/": {}
			"/_internal": {}
			"/[locale]": { params: { locale: string } }
			"/about": {}
			"/blog": {}
			"/blog/[slug]": { params: { slug: string } }
			"/dashboard": {}
			"/deep-cache": {}
			"/deep-cache/uncached": {}
			"/files/[...path]": { params: { path: string[] } }
			"/login": {}
			"/optional-locale/[[locale]]": { params: { locale: string | undefined } }
			"/users/[id]": { params: { id: string } }
		}
		routeModules: {
			"_admin_": typeof import("../routes/_admin_/admin.root-layout")["route"]
			"_admin_/dashboard": typeof import("../routes/_admin_/dashboard/dash.page")["route"]
			"_root_": typeof import("../routes/_root_/root.root-layout")["route"]
			"_root_/": typeof import("../routes/_root_/home.page")["route"]
			"_root_/_internal": typeof import("../routes/_root_/[_]internal/hidden.page")["route"]
			"_root_/(auth)": typeof import("../routes/_root_/(auth)/auth.layout")["route"]
			"_root_/(auth)/login": typeof import("../routes/_root_/(auth)/login/login.page")["route"]
			"_root_/(blog)": typeof import("../routes/_root_/(blog)/blog.layout")["route"]
			"_root_/(blog)/blog": typeof import("../routes/_root_/(blog)/blog/list.page")["route"]
			"_root_/(blog)/blog/[slug]": typeof import("../routes/_root_/(blog)/blog/[slug]/post.page")["route"]
			"_root_/(dc)": typeof import("../routes/_root_/(dc)/dc.layout")["route"]
			"_root_/(dc)/(inner)": typeof import("../routes/_root_/(dc)/(inner)/inner.layout")["route"]
			"_root_/(dc)/(inner)/(leaf)": typeof import("../routes/_root_/(dc)/(inner)/(leaf)/leaf.layout")["route"]
			"_root_/(dc)/(inner)/(leaf)/deep-cache": typeof import("../routes/_root_/(dc)/(inner)/(leaf)/deep-cache/index.page")["route"]
			"_root_/(dc)/(inner)/(leaf)/deep-cache/uncached": typeof import("../routes/_root_/(dc)/(inner)/(leaf)/deep-cache/uncached/uncached.page")["route"]
			"_root_/about": typeof import("../routes/_root_/about/about.page")["route"]
			"_root_/files/[...path]": typeof import("../routes/_root_/files/[...path]/files.page")["route"]
			"_root_/optional-locale/[[locale]]": typeof import("../routes/_root_/optional-locale/[[locale]]/opt.page")["route"]
			"_root_/users/[id]": typeof import("../routes/_root_/users/[id]/user.page")["route"]
			"[locale]/_root_": typeof import("../routes/[locale]/_root_/locale.root-layout")["route"]
			"[locale]/_root_/": typeof import("../routes/[locale]/_root_/locale-home.page")["route"]
		}
		routeParents: {
			"_admin_": []
			"_admin_/dashboard": ["_admin_"]
			"_root_": []
			"_root_/": ["_root_"]
			"_root_/_internal": ["_root_"]
			"_root_/(auth)": ["_root_"]
			"_root_/(auth)/login": ["_root_", "_root_/(auth)"]
			"_root_/(blog)": ["_root_"]
			"_root_/(blog)/blog": ["_root_", "_root_/(blog)"]
			"_root_/(blog)/blog/[slug]": ["_root_", "_root_/(blog)"]
			"_root_/(dc)": ["_root_"]
			"_root_/(dc)/(inner)": ["_root_", "_root_/(dc)"]
			"_root_/(dc)/(inner)/(leaf)": ["_root_", "_root_/(dc)", "_root_/(dc)/(inner)"]
			"_root_/(dc)/(inner)/(leaf)/deep-cache": ["_root_", "_root_/(dc)", "_root_/(dc)/(inner)", "_root_/(dc)/(inner)/(leaf)"]
			"_root_/(dc)/(inner)/(leaf)/deep-cache/uncached": ["_root_", "_root_/(dc)", "_root_/(dc)/(inner)", "_root_/(dc)/(inner)/(leaf)"]
			"_root_/about": ["_root_"]
			"_root_/files/[...path]": ["_root_"]
			"_root_/optional-locale/[[locale]]": ["_root_"]
			"_root_/users/[id]": ["_root_"]
			"[locale]/_root_": []
			"[locale]/_root_/": ["[locale]/_root_"]
		}
		env: Parameters<typeof _FlareHandler["fetch"]>[1]
		serverContext: Awaited<ReturnType<NonNullable<typeof _FlareHandler["serverContext"]>>>
	}
}
