/* Auto-generated by flare — do not edit */
import type { RouteData, TreeNode } from "@ecomet/flare/codegen"
import type { handler as _FlareHandler } from "../server"

const E: Record<string, TreeNode> = Object.create(null)

const O0 = {} as const

const R0: RouteData = {
	e: "route",
	f: "src/routes/index.tsx",
	o: O0,
	p: () => import("../routes/index").then(m => ({ default: m.route })),
	t: "r",
	v: "/",
	x: "_root_/",
}

export const routeTree: TreeNode = { r: R0, s: E }

export const layouts: Record<string, () => Promise<{ default: unknown }>> = {
	"_root_": () => import("../routes/_root_").then(m => ({ default: m["route"] })),
}

export const layoutModuleIds: Record<string, string> = {
	"_root_": "src/routes/_root_.tsx",
}

/* Route type registry — auto-generated */
declare module "@ecomet/flare/codegen" {
	interface FlareRegister {
		routes: {
			"/": {}
		}
		routeModules: {
			"_root_": typeof import("../routes/_root_")["route"]
			"_root_/": typeof import("../routes/index")["route"]
		}
		routeParents: {
			"_root_": []
			"_root_/": ["_root_"]
		}
		env: Parameters<typeof _FlareHandler["fetch"]>[1]
		serverContext: Awaited<ReturnType<NonNullable<typeof _FlareHandler["serverContext"]>>>
	}
}
