/**
 * QueryClient Registry
 *
 * Type-safe declaration for whether QueryClient is available in the app.
 * The route generator automatically detects queryClientGetter in flare.ts
 * and generates the appropriate module augmentation.
 *
 * Generated in _gen/flare.types.gen.ts:
 * ```typescript
 * declare module "@flare/v0/query-client/registry" {
 *   interface FlareQueryClientRegistry {
 *     queryClient: QueryClient
 *   }
 * }
 * ```
 */

import type { QueryClient } from "@tanstack/query-core"

export type { QueryClient }

/**
 * Module augmentation interface for QueryClient registration.
 * Default: empty interface → queryClient is null
 * With augmentation: { queryClient: QueryClient } → queryClient is QueryClient
 *
 * This is auto-generated by the route generator based on flare.ts config.
 */

export interface FlareQueryClientRegistry {}

/**
 * Helper type to safely extract queryClient from registry
 */
type GetQueryClient<T> = T extends { queryClient: infer U } ? U : null

/**
 * Resolved QueryClient type based on registry.
 * - If queryClient key exists in registry → QueryClient (exact, non-null)
 * - If registry is empty → null (exact, non-QueryClient)
 */
export type ResolvedQueryClient = GetQueryClient<FlareQueryClientRegistry>
