/* @generated by flare — do not edit. checksum: e8bbc1798711 */
import type { RouteData, TreeNode } from "flare/codegen"
import type { handler as _FlareHandler } from "../server"

const E: Record<string, TreeNode> = Object.create(null)
function S(o: Record<string, TreeNode>): Record<string, TreeNode> { return Object.assign(Object.create(null), o) }

const O0 = {} as const

const R0: RouteData = {
	e: "route",
	f: "src/routes/about.tsx",
	o: O0,
	p: () => import("../routes/about").then(m => ({ default: m.route })),
	t: "r",
	v: "/about",
	x: "_root_/about",
}
const R1: RouteData = {
	e: "route",
	f: "src/routes/context.tsx",
	o: O0,
	p: () => import("../routes/context").then(m => ({ default: m.route })),
	t: "r",
	v: "/context",
	x: "_root_/context",
}
const R2: RouteData = {
	e: "route",
	f: "src/routes/deferred.tsx",
	o: O0,
	p: () => import("../routes/deferred").then(m => ({ default: m.route })),
	t: "r",
	v: "/deferred",
	x: "_root_/deferred",
}
const R3: RouteData = {
	e: "route",
	f: "src/routes/echo.tsx",
	o: O0,
	p: () => import("../routes/echo").then(m => ({ default: m.route })),
	t: "r",
	v: "/echo",
	x: "_root_/echo",
}
const R4: RouteData = {
	e: "route",
	f: "src/routes/encoding.tsx",
	o: O0,
	p: () => import("../routes/encoding").then(m => ({ default: m.route })),
	t: "r",
	v: "/encoding",
	x: "_root_/encoding",
}
const R5: RouteData = {
	e: "route",
	f: "src/routes/error-test.tsx",
	o: O0,
	p: () => import("../routes/error-test").then(m => ({ default: m.route })),
	t: "r",
	v: "/error-test",
	x: "_root_/error-test",
}
const R6: RouteData = {
	e: "route",
	f: "src/routes/hash.tsx",
	o: O0,
	p: () => import("../routes/hash").then(m => ({ default: m.route })),
	t: "r",
	v: "/hash",
	x: "_root_/hash",
}
const R7: RouteData = {
	e: "route",
	f: "src/routes/index.tsx",
	o: O0,
	p: () => import("../routes/index").then(m => ({ default: m.route })),
	t: "r",
	v: "/",
	x: "_root_/",
}
const R8: RouteData = {
	e: "route",
	f: "src/routes/json-edge.tsx",
	o: O0,
	p: () => import("../routes/json-edge").then(m => ({ default: m.route })),
	t: "r",
	v: "/json-edge",
	x: "_root_/json-edge",
}
const R9: RouteData = {
	e: "route",
	f: "src/routes/multi-cookie.tsx",
	o: O0,
	p: () => import("../routes/multi-cookie").then(m => ({ default: m.route })),
	t: "r",
	v: "/multi-cookie",
	x: "_root_/multi-cookie",
}
const R10: RouteData = {
	e: "route",
	f: "src/routes/old-page.tsx",
	o: O0,
	p: () => import("../routes/old-page").then(m => ({ default: m.route })),
	t: "r",
	v: "/old-page",
	x: "_root_/old-page",
}
const R11: RouteData = {
	e: "route",
	f: "src/routes/preloaded.tsx",
	o: O0,
	p: () => import("../routes/preloaded").then(m => ({ default: m.route })),
	t: "r",
	v: "/preloaded",
	x: "_root_/preloaded",
}
const R12: RouteData = {
	e: "route",
	f: "src/routes/search.tsx",
	o: O0,
	p: () => import("../routes/search").then(m => ({ default: m.route })),
	t: "r",
	v: "/search",
	x: "_root_/search",
}
const R13: RouteData = {
	e: "route",
	f: "src/routes/seo.tsx",
	o: O0,
	p: () => import("../routes/seo").then(m => ({ default: m.route })),
	t: "r",
	v: "/seo",
	x: "_root_/seo",
}
const R14: RouteData = {
	e: "route",
	f: "src/routes/streams.tsx",
	o: O0,
	p: () => import("../routes/streams").then(m => ({ default: m.route })),
	t: "r",
	v: "/streams",
	x: "_root_/streams",
}
const R15: RouteData = {
	e: "route",
	f: "src/routes/time.tsx",
	o: O0,
	p: () => import("../routes/time").then(m => ({ default: m.route })),
	t: "r",
	v: "/time",
	x: "_root_/time",
}
const R16: RouteData = {
	e: "route",
	f: "src/routes/dashboard/index.tsx",
	o: O0,
	p: () => import("../routes/dashboard/index").then(m => ({ default: m.route })),
	t: "r",
	v: "/dashboard",
	x: "_root_/(dashboard)/dashboard",
}
const R17: RouteData = {
	e: "route",
	f: "src/routes/dashboard/settings.tsx",
	o: O0,
	p: () => import("../routes/dashboard/settings").then(m => ({ default: m.route })),
	t: "r",
	v: "/dashboard/settings",
	x: "_root_/(dashboard)/dashboard/settings",
}
const R18: RouteData = {
	e: "route",
	f: "src/routes/decode/[slug].tsx",
	o: O0,
	p: () => import("../routes/decode/[slug]").then(m => ({ default: m.route })),
	t: "r",
	v: "/decode/[slug]",
	x: "_root_/decode/[slug]",
}
const R19: RouteData = {
	e: "route",
	f: "src/routes/files/[...path].tsx",
	o: O0,
	p: () => import("../routes/files/[...path]").then(m => ({ default: m.route })),
	t: "r",
	v: "/files/[...path]",
	x: "_root_/files/[...path]",
}
const R20: RouteData = {
	e: "route",
	f: "src/routes/users/[id].tsx",
	o: O0,
	p: () => import("../routes/users/[id]").then(m => ({ default: m.route })),
	t: "r",
	v: "/users/[id]",
	x: "_root_/users/[id]",
}

export const routeTree: TreeNode = { r: R7, s: S({ about: { r: R0, s: E }, context: { r: R1, s: E }, deferred: { r: R2, s: E }, echo: { r: R3, s: E }, encoding: { r: R4, s: E }, "error-test": { r: R5, s: E }, hash: { r: R6, s: E }, "json-edge": { r: R8, s: E }, "multi-cookie": { r: R9, s: E }, "old-page": { r: R10, s: E }, preloaded: { r: R11, s: E }, search: { r: R12, s: E }, seo: { r: R13, s: E }, streams: { r: R14, s: E }, time: { r: R15, s: E }, dashboard: { r: R16, s: S({ settings: { r: R17, s: E } }) }, decode: { p: { n: "slug", r: R18, s: E }, s: E }, files: { c: { n: "path", r: R19, s: E }, s: E }, users: { p: { n: "id", r: R20, s: E }, s: E } }) }

export const layouts: Record<string, () => Promise<{ default: unknown }>> = {
	"_root_": () => import("../routes/_root_").then(m => ({ default: m["route"] })),
	"_root_/(dashboard)": () => import("../routes/dashboard/_layout_").then(m => ({ default: m["route"] })),
}

export const layoutModuleIds: Record<string, string> = {
	"_root_": "src/routes/_root_.tsx",
	"_root_/(dashboard)": "src/routes/dashboard/_layout_.tsx",
}

/* Route type registry — auto-generated */
declare module "flare/codegen" {
	interface FlareRegister {
		routes: {
			"/": {}
			"/about": {}
			"/context": {}
			"/dashboard": {}
			"/dashboard/settings": {}
			"/decode/[slug]": { params: { slug: string } }
			"/deferred": {}
			"/echo": {}
			"/encoding": {}
			"/error-test": {}
			"/files/[...path]": { params: { path: string[] } }
			"/hash": {}
			"/json-edge": {}
			"/multi-cookie": {}
			"/old-page": {}
			"/preloaded": {}
			"/search": {}
			"/seo": {}
			"/streams": {}
			"/time": {}
			"/users/[id]": { params: { id: string } }
		}
		routeModules: {
			"_root_": typeof import("../routes/_root_")["route"]
			"_root_/": typeof import("../routes/index")["route"]
			"_root_/(dashboard)": typeof import("../routes/dashboard/_layout_")["route"]
			"_root_/(dashboard)/dashboard": typeof import("../routes/dashboard/index")["route"]
			"_root_/(dashboard)/dashboard/settings": typeof import("../routes/dashboard/settings")["route"]
			"_root_/about": typeof import("../routes/about")["route"]
			"_root_/context": typeof import("../routes/context")["route"]
			"_root_/decode/[slug]": typeof import("../routes/decode/[slug]")["route"]
			"_root_/deferred": typeof import("../routes/deferred")["route"]
			"_root_/echo": typeof import("../routes/echo")["route"]
			"_root_/encoding": typeof import("../routes/encoding")["route"]
			"_root_/error-test": typeof import("../routes/error-test")["route"]
			"_root_/files/[...path]": typeof import("../routes/files/[...path]")["route"]
			"_root_/hash": typeof import("../routes/hash")["route"]
			"_root_/json-edge": typeof import("../routes/json-edge")["route"]
			"_root_/multi-cookie": typeof import("../routes/multi-cookie")["route"]
			"_root_/old-page": typeof import("../routes/old-page")["route"]
			"_root_/preloaded": typeof import("../routes/preloaded")["route"]
			"_root_/search": typeof import("../routes/search")["route"]
			"_root_/seo": typeof import("../routes/seo")["route"]
			"_root_/streams": typeof import("../routes/streams")["route"]
			"_root_/time": typeof import("../routes/time")["route"]
			"_root_/users/[id]": typeof import("../routes/users/[id]")["route"]
		}
		routeParents: {
			"_root_": []
			"_root_/": ["_root_"]
			"_root_/(dashboard)": ["_root_"]
			"_root_/(dashboard)/dashboard": ["_root_", "_root_/(dashboard)"]
			"_root_/(dashboard)/dashboard/settings": ["_root_", "_root_/(dashboard)"]
			"_root_/about": ["_root_"]
			"_root_/context": ["_root_"]
			"_root_/decode/[slug]": ["_root_"]
			"_root_/deferred": ["_root_"]
			"_root_/echo": ["_root_"]
			"_root_/encoding": ["_root_"]
			"_root_/error-test": ["_root_"]
			"_root_/files/[...path]": ["_root_"]
			"_root_/hash": ["_root_"]
			"_root_/json-edge": ["_root_"]
			"_root_/multi-cookie": ["_root_"]
			"_root_/old-page": ["_root_"]
			"_root_/preloaded": ["_root_"]
			"_root_/search": ["_root_"]
			"_root_/seo": ["_root_"]
			"_root_/streams": ["_root_"]
			"_root_/time": ["_root_"]
			"_root_/users/[id]": ["_root_"]
		}
		env: Parameters<typeof _FlareHandler["fetch"]>[1]
		serverContext: Awaited<ReturnType<NonNullable<typeof _FlareHandler["serverContext"]>>>
	}
}
