/* Auto-generated by @ecomet/flare — do not edit */
import type { RouteData, TreeNode } from "@ecomet/flare"

const E: Record<string, TreeNode> = {}

export const routeTree: TreeNode = { s: E }

export const layouts: Record<string, () => Promise<{ default: unknown }>> = {}

/* Route type registry — auto-generated */
declare module "@ecomet/flare" {
	interface FlareRegister {
		routes: {}
		routeModules: {}
		routeParents: {}
	}
}
