/* @generated by flare — do not edit. checksum: 41e96d706467 */
/* Auto-generated by flare — do not edit */
import type { InferParams, InferSearchParams, RouteData, TreeNode } from "@lovrozagar/flare/codegen"
import type { server as _FlareHandler } from "../server"

const E: Record<string, TreeNode> = Object.create(null)
function S(o: Record<string, TreeNode>): Record<string, TreeNode> { return Object.assign(Object.create(null), o) }

const O0 = {} as const

const R0: RouteData = {
	e: "route",
	f: "src/routes/[[locale]]/_root_/(main)/about/about-page.tsx",
	o: O0,
	p: () => import("../routes/[[locale]]/_root_/(main)/about/about-page").then(m => ({ default: m.route })),
	t: "r",
	v: "/[[locale]]/about",
	x: "[[locale]]/_root_/(main)/about",
}
const R1: RouteData = {
	e: "route",
	f: "src/routes/[[locale]]/_root_/(main)/index/index-page.tsx",
	o: O0,
	p: () => import("../routes/[[locale]]/_root_/(main)/index/index-page").then(m => ({ default: m.route })),
	t: "r",
	v: "/[[locale]]",
	x: "[[locale]]/_root_/(main)/",
}
const R2: RouteData = {
	e: "route",
	f: "src/routes/[[locale]]/_root_/(vt)/vt-shell/[id]/vt-item-page.tsx",
	o: O0,
	p: () => import("../routes/[[locale]]/_root_/(vt)/vt-shell/[id]/vt-item-page").then(m => ({ default: m.route })),
	t: "r",
	v: "/[[locale]]/vt-shell/[id]",
	x: "[[locale]]/_root_/(vt)/vt-shell/[id]",
}
const R3: RouteData = {
	e: "route",
	f: "src/routes/[[locale]]/_root_/(vt)/vt-shell/a/vt-a-page.tsx",
	o: O0,
	p: () => import("../routes/[[locale]]/_root_/(vt)/vt-shell/a/vt-a-page").then(m => ({ default: m.route })),
	t: "r",
	v: "/[[locale]]/vt-shell/a",
	x: "[[locale]]/_root_/(vt)/vt-shell/a",
}
const R4: RouteData = {
	e: "route",
	f: "src/routes/[[locale]]/_root_/(vt)/vt-shell/b/vt-b-page.tsx",
	o: O0,
	p: () => import("../routes/[[locale]]/_root_/(vt)/vt-shell/b/vt-b-page").then(m => ({ default: m.route })),
	t: "r",
	v: "/[[locale]]/vt-shell/b",
	x: "[[locale]]/_root_/(vt)/vt-shell/b",
}
const R5: RouteData = {
	e: "route",
	f: "src/routes/[[locale]]/_root_/offline/offline-page.tsx",
	o: O0,
	p: () => import("../routes/[[locale]]/_root_/offline/offline-page").then(m => ({ default: m.route })),
	t: "r",
	v: "/[[locale]]/offline",
	x: "[[locale]]/_root_/offline",
}

export const routeTree: TreeNode = { q: { n: "locale", r: R1, s: S({ about: { r: R0, s: E }, "vt-shell": { p: { n: "id", r: R2, s: E }, s: S({ a: { r: R3, s: E }, b: { r: R4, s: E } }) }, offline: { r: R5, s: E } }) }, s: E }

export const layouts: Record<string, () => Promise<{ default: unknown }>> = {
	"[[locale]]/_root_/(main)": () => import("../routes/[[locale]]/_root_/(main)/main-layout").then(m => ({ default: m["route"] })),
	"[[locale]]/_root_/(vt)": () => import("../routes/[[locale]]/_root_/(vt)/vt-layout").then(m => ({ default: m["route"] })),
	"[[locale]]/_root_": () => import("../routes/[[locale]]/_root_/root-layout").then(m => ({ default: m["rootLayout"] })),
	"[[locale]]": () => import("../routes/[[locale]]/locale").then(m => ({ default: m["pathSegment"] })),
}

export const layoutModuleIds: Record<string, string> = {
	"[[locale]]/_root_/(main)": "src/routes/[[locale]]/_root_/(main)/main-layout.tsx",
	"[[locale]]/_root_/(vt)": "src/routes/[[locale]]/_root_/(vt)/vt-layout.tsx",
	"[[locale]]/_root_": "src/routes/[[locale]]/_root_/root-layout.tsx",
	"[[locale]]": "src/routes/[[locale]]/locale.tsx",
}

/* Route type registry — auto-generated */
declare module "@lovrozagar/flare/codegen" {
	interface FlareRegister {
		routes: {
			"/[[locale]]": { params: { locale: string | undefined } }
			"/[[locale]]/about": { params: { locale: string | undefined } }
			"/[[locale]]/offline": { params: { locale: string | undefined } }
			"/[[locale]]/vt-shell/[id]": { params: { id: string, locale: string | undefined } }
			"/[[locale]]/vt-shell/a": { params: { locale: string | undefined } }
			"/[[locale]]/vt-shell/b": { params: { locale: string | undefined } }
		}
		routeModules: {
			"[[locale]]": typeof import("../routes/[[locale]]/locale")["pathSegment"]
			"[[locale]]/_root_": typeof import("../routes/[[locale]]/_root_/root-layout")["rootLayout"]
			"[[locale]]/_root_/(main)": typeof import("../routes/[[locale]]/_root_/(main)/main-layout")["route"]
			"[[locale]]/_root_/(main)/": typeof import("../routes/[[locale]]/_root_/(main)/index/index-page")["route"]
			"[[locale]]/_root_/(main)/about": typeof import("../routes/[[locale]]/_root_/(main)/about/about-page")["route"]
			"[[locale]]/_root_/(vt)": typeof import("../routes/[[locale]]/_root_/(vt)/vt-layout")["route"]
			"[[locale]]/_root_/(vt)/vt-shell/[id]": typeof import("../routes/[[locale]]/_root_/(vt)/vt-shell/[id]/vt-item-page")["route"]
			"[[locale]]/_root_/(vt)/vt-shell/a": typeof import("../routes/[[locale]]/_root_/(vt)/vt-shell/a/vt-a-page")["route"]
			"[[locale]]/_root_/(vt)/vt-shell/b": typeof import("../routes/[[locale]]/_root_/(vt)/vt-shell/b/vt-b-page")["route"]
			"[[locale]]/_root_/offline": typeof import("../routes/[[locale]]/_root_/offline/offline-page")["route"]
		}
		routeParents: {
			"[[locale]]": []
			"[[locale]]/_root_": []
			"[[locale]]/_root_/(main)": ["[[locale]]/_root_"]
			"[[locale]]/_root_/(main)/": ["[[locale]]/_root_", "[[locale]]/_root_/(main)"]
			"[[locale]]/_root_/(main)/about": ["[[locale]]/_root_", "[[locale]]/_root_/(main)"]
			"[[locale]]/_root_/(vt)": ["[[locale]]/_root_"]
			"[[locale]]/_root_/(vt)/vt-shell/[id]": ["[[locale]]/_root_", "[[locale]]/_root_/(vt)"]
			"[[locale]]/_root_/(vt)/vt-shell/a": ["[[locale]]/_root_", "[[locale]]/_root_/(vt)"]
			"[[locale]]/_root_/(vt)/vt-shell/b": ["[[locale]]/_root_", "[[locale]]/_root_/(vt)"]
			"[[locale]]/_root_/offline": ["[[locale]]/_root_"]
		}
		routeSearchParams: {
			"/[[locale]]/about": InferSearchParams<typeof import("../routes/[[locale]]/_root_/(main)/about/about-page")["route"]>
		}
		routeParams: {
			"/[[locale]]/about": InferParams<typeof import("../routes/[[locale]]/_root_/(main)/about/about-page")["route"]>
		}
		env: NonNullable<(typeof _FlareHandler)["~flare"]>["env"]
		serverContext: NonNullable<(typeof _FlareHandler)["~flare"]>["serverContext"]
	}
}
