/* @generated by flare — do not edit. checksum: 2f74c6b0a6af */
/* Auto-generated by flare — do not edit */
import type { InferParams, InferSearchParams, RouteData, TreeNode } from "@lovrozagar/flare/codegen"
import type { server as _FlareHandler } from "../server"

const E: Record<string, TreeNode> = Object.create(null)
function S(o: Record<string, TreeNode>): Record<string, TreeNode> { return Object.assign(Object.create(null), o) }

const O0 = {} as const

const R0: RouteData = {
	e: "route",
	f: "src/routes/[[locale]]/_root_/offline/offline-page.tsx",
	o: O0,
	p: () => import("../routes/[[locale]]/_root_/offline/offline-page").then(m => ({ default: m.route })),
	t: "r",
	v: "/[[locale]]/offline",
	x: "[[locale]]/_root_/offline",
}
const R1: RouteData = {
	e: "route",
	f: "src/routes/[[locale]]/_root_/(main)/about/about-page.tsx",
	o: O0,
	p: () => import("../routes/[[locale]]/_root_/(main)/about/about-page").then(m => ({ default: m.route })),
	t: "r",
	v: "/[[locale]]/about",
	x: "[[locale]]/_root_/(main)/about",
}
const R2: RouteData = {
	e: "route",
	f: "src/routes/[[locale]]/_root_/(main)/index/index-page.tsx",
	o: O0,
	p: () => import("../routes/[[locale]]/_root_/(main)/index/index-page").then(m => ({ default: m.route })),
	t: "r",
	v: "/[[locale]]",
	x: "[[locale]]/_root_/(main)/",
}

export const routeTree: TreeNode = { q: { n: "locale", r: R2, s: S({ offline: { r: R0, s: E }, about: { r: R1, s: E } }) }, s: E }

export const layouts: Record<string, () => Promise<{ default: unknown }>> = {
	"[[locale]]": () => import("../routes/[[locale]]/locale").then(m => ({ default: m["pathSegment"] })),
	"[[locale]]/_root_": () => import("../routes/[[locale]]/_root_/root-layout").then(m => ({ default: m["rootLayout"] })),
	"[[locale]]/_root_/(main)": () => import("../routes/[[locale]]/_root_/(main)/main-layout").then(m => ({ default: m["route"] })),
}

export const layoutModuleIds: Record<string, string> = {
	"[[locale]]": "src/routes/[[locale]]/locale.tsx",
	"[[locale]]/_root_": "src/routes/[[locale]]/_root_/root-layout.tsx",
	"[[locale]]/_root_/(main)": "src/routes/[[locale]]/_root_/(main)/main-layout.tsx",
}

/* Route type registry — auto-generated */
declare module "@lovrozagar/flare/codegen" {
	interface FlareRegister {
		routes: {
			"/[[locale]]": { params: { locale: string | undefined } }
			"/[[locale]]/about": { params: { locale: string | undefined } }
			"/[[locale]]/offline": { params: { locale: string | undefined } }
		}
		routeModules: {
			"[[locale]]": typeof import("../routes/[[locale]]/locale")["pathSegment"]
			"[[locale]]/_root_": typeof import("../routes/[[locale]]/_root_/root-layout")["rootLayout"]
			"[[locale]]/_root_/(main)": typeof import("../routes/[[locale]]/_root_/(main)/main-layout")["route"]
			"[[locale]]/_root_/(main)/": typeof import("../routes/[[locale]]/_root_/(main)/index/index-page")["route"]
			"[[locale]]/_root_/(main)/about": typeof import("../routes/[[locale]]/_root_/(main)/about/about-page")["route"]
			"[[locale]]/_root_/offline": typeof import("../routes/[[locale]]/_root_/offline/offline-page")["route"]
		}
		routeParents: {
			"[[locale]]": []
			"[[locale]]/_root_": []
			"[[locale]]/_root_/(main)": ["[[locale]]/_root_"]
			"[[locale]]/_root_/(main)/": ["[[locale]]/_root_", "[[locale]]/_root_/(main)"]
			"[[locale]]/_root_/(main)/about": ["[[locale]]/_root_", "[[locale]]/_root_/(main)"]
			"[[locale]]/_root_/offline": ["[[locale]]/_root_"]
		}
		routeSearchParams: {
			"/[[locale]]/about": InferSearchParams<typeof import("../routes/[[locale]]/_root_/(main)/about/about-page")["route"]>
		}
		routeParams: {
			"/[[locale]]/about": InferParams<typeof import("../routes/[[locale]]/_root_/(main)/about/about-page")["route"]>
		}
		env: Parameters<typeof _FlareHandler["fetch"]>[1]
		serverContext: Awaited<ReturnType<NonNullable<typeof _FlareHandler["serverContext"]>>>
	}
}
