import { compileToSource, compileToTables, mergeConfigs } from "../styles/cn-vendor/compiler.ts";
import { getDefaultCnConfig } from "../styles/cn-vendor/default-config.generated.ts";
import { createEngine, wrapClsx } from "../styles/cn-vendor/engine.ts";
import { themeFromCss } from "../styles/cn-vendor/theme-css.ts";
import { resolveStylesheetPath } from "./tw-compile.ts";

export interface ThemeCn {
	/** `cn` merging with the app theme's scales (custom radius, spacing, font size, shadow names). */
	cn: (...inputs: Parameters<ReturnType<typeof wrapClsx>>) => string;
	/** Same merge for one space-separated string — what the compile-time static merge runs. */
	mergeString: (input: string) => string;
	/** Every stylesheet read, so dev can rebuild when one changes. */
	files: string[];
	/** An ES module whose default export is the compiled tables, in the shape of `cn-vendor/tables.generated.ts`. */
	source: string;
}

/**
 * Compile `cn` merge tables from a Tailwind v4 entry stylesheet: the default tailwind-merge config
 * extended (or overridden, for `--<ns>-*: initial`) by the `@theme` names it and its relative and
 * package imports declare.
 */
export function createThemeCn(cssPath: string): ThemeCn {
	const { extension, files } = themeFromCss([cssPath], (specifier, fromDir) =>
		resolveStylesheetPath(specifier, fromDir),
	);
	const config = mergeConfigs(getDefaultCnConfig(), extension);
	const { tables, validatorImpls, prefix } = compileToTables(config);
	const engine = createEngine(tables, validatorImpls, { prefix });
	return {
		cn: wrapClsx(engine.mergeString, engine),
		files,
		mergeString: engine.mergeString,
		source: compileToSource(config, { banner: `// GENERATED by @lovrozagar/flare from ${cssPath}. Do not edit.` }),
	};
}
