/* @generated by flare — do not edit. checksum: b1228bc57153 */
/* Auto-generated by flare — do not edit */
import type { TreeNode } from "@lovrozagar/flare/codegen"
import type { handler as _FlareHandler } from "../server"

const E: Record<string, TreeNode> = Object.create(null)

export const routeTree: TreeNode = { s: E }

export const layouts: Record<string, () => Promise<{ default: unknown }>> = {}
export const layoutModuleIds: Record<string, string> = {}

/* Route type registry — auto-generated */
declare module "@lovrozagar/flare/codegen" {
	interface FlareRegister {
		routes: {
		}
		routeModules: {
		}
		routeParents: {
		}
		env: Parameters<typeof _FlareHandler["fetch"]>[1]
		serverContext: Awaited<ReturnType<NonNullable<typeof _FlareHandler["serverContext"]>>>
	}
}
